### ISSUE TITLE
Add factory for phase boundary nodes

### ISSUE THREAD

**Issue by Mortal** [thomasmoelhave/tpie#154]
We have enough users implementing push->push phase boundary nodes that the framework should provide a factory that can instantiate the two nodes making up the boundary. See for instance the non-passive buffer and reverser. See branch phase_boundary.

**Comment by svendcsvendsen** [comment]
Jakob has recently implemented the factory helper `tpie::pipelining::split_factory` that solves this problem. It is already used by `buffer`, `reverser` etc.
