### ISSUE TITLE
tpie::stack<T> peek()

### ISSUE THREAD

**Issue by yjwoo14** [thomasmoelhave/tpie#173]
While I'm executing the following code (which I didn't write), I found an issue (perhaps it's not a bug but just wrong way to use peek() ) 
```
if (stack->peek(&item) == tpie::ami::NO_ERROR) 
```
When the stack is empty, is peek() supposed to try to read disk? 
This code is repeatedly called during a time forward sweep and this causes significant performance loss.

**Comment by thomasmoelhave** [comment]
This code seems to use the legacy AMI_stack interface, which should return END_OF_STREAM if the stack is empty, according to the docstring:
https://github.com/thomasmoelhave/tpie/blob/master/tpie/stack.h#L232
If it does return END_OF_STREAM there is likely no actual semantic bug, but I wonder if the legacy interface could be implemented in a way that avoids the disk reads that you are seeing.

**Comment by svendcsvendsen** [comment]
The `ami::stack` now runs `.empty()` on the internal stack before trying to pop or peek. I did a [quick test](https://gist.github.com/cf494beecbcfdff49ea7) and it reduced running time from ~23 seconds to ~0.7 seconds.
