### ISSUE TITLE
compressor_thread::m_preferredCompression is snappy, causing a warning when snappy is not available

### ISSUE THREAD

**Issue by freekvw** [thomasmoelhave/tpie#179]
Basically, when you don't have snappy installed, tpie will by default output a warning
"get_compression_scheme_snappy: No snappy support; return none instead."
I don't really care how it's solved, but the warning is a little annoying.

**Comment by svendcsvendsen** [comment]
The message now outputs to `log_debug()` instead of `log_warning()`.
