### ISSUE TITLE
Setting file permissions on created files

### ISSUE THREAD

**Issue by thomasmoelhave** [thomasmoelhave/tpie#180]
The POSIX driver sets the file permissions in the [open call](https://github.com/thomasmoelhave/tpie/blob/f2160da0fd0e28436d93941c09ba452879e521bb/tpie/file_accessor/posix.inl#L121). This seems to go all the way back to the old stuff in portability.h. Is there a good reason for this behavior (instead of the default umask)? On my system the outcome is that tpie streams created by my process are not group-readable although all the other files created by the process are, that's a little annoying.

**Comment by Mortal** [comment]
I don't think there is a good reason for that behavior. Obeying umask seems like a sane change to me.

**Comment by svendcsvendsen** [comment]
I agree. I'll take a look at it this week.

**Comment by svendcsvendsen** [comment]
I've changed the POSIX driver so that all files created have permissions set to `0777 & ~umask`, i.e. the umask dictates the flags
