### ISSUE TITLE
#define final breaks usage of boost multi-index

### ISSUE THREAD

**Issue by hendrik-cliqz** [thomasmoelhave/tpie#184]
Hi,

I am using TPIE in one of my projects together with boost, the following commit:

https://github.com/thomasmoelhave/tpie/commit/e5fa6cdf09a60caa3d2c5ac744b5e5141e4c182d

breaks the build as it does a

    #define final

That breaks boost further down here:

    /usr/include/boost/multi_index/detail/header_holder.hpp:41:16: error: expected unqualified-id before ')' token

    template<typename NodeTypePtr,typename Final>
    struct header_holder:private noncopyable
    {
      header_holder():member(final().allocate_node()){}
      ~header_holder(){final().deallocate_node(&*member);}
    
      NodeTypePtr member;

    private:
      Final& final(){return *static_cast<Final*>(this);}
    };

See also this post:
http://stackoverflow.com/questions/10082572/hello-to-boost-multi-index

To reproduce just do the following includes:

works:

    #include <boost/property_tree/ptree.hpp>
    #include "tpie/serialization_sorter.h"

breaks due to re-definition of final:

    #include "tpie/serialization_sorter.h"
    #include <boost/property_tree/ptree.hpp>

**Comment by antialize** [comment]
We could fix this issue by defining TPIE_FINAL and TPIE_OVERRIDE, and use that throughout.
We have been talking about deprecating support for visual studio before 2013, and for gcc and clang without -std=c++11.  Since none of us are testing such targets. If we did that we would not need the define as we could then just assume it to work. Tough I guess it would not work in your case?

**Comment by hendrik-cliqz** [comment]
It would work for me as I am using C++11. My main platforms are Linux and Mac, Windows probably does not compile, I never tried it.

IMHO it is a fair deal to rather drop platforms which can not be tested and that might not be used at all.

Your decision, I am fine with dropping the mentioned old platforms.

**Comment by antialize** [comment]
If you are allready using c++11. I do not see how you can get this bug. The defines should only be specified when not in c++11 mode.  Can you try to compile https://github.com/thomasmoelhave/tpie/blob/master/cpp0xtest/override_keyword.cpp with exactly the same flags as you are using when compiling tpie. It should compile without errors or warnings.

**Comment by hendrik-cliqz** [comment]
FYI the compile that breaks:

    g++ -o src/cpp/dictionarycompiler/dictionarycompiler.o -c -std=c++11 -O3 -I3rdparty/rapidjson/include     -I3rdparty/msgpack-c/include -I3rdparty/tpie/build/install/include -Isrc/cpp src/cpp/dictionarycompiler/dictionarycompiler.cpp
    In file included from /usr/include/boost/multi_index/detail/node_type.hpp:22:0,
                 from /usr/include/boost/multi_index/detail/index_base.hpp:24,
                 from /usr/include/boost/multi_index/detail/base_type.hpp:21,
                 from /usr/include/boost/multi_index_container.hpp:34,
                 from /usr/include/boost/property_tree/ptree.hpp:21,
                 from src/cpp/dictionary/fsa/generator.h:13,
                 from src/cpp/dictionary/dictionary_compiler.h:18,
                 from src/cpp/dictionarycompiler/dictionarycompiler.cpp:15:
    /usr/include/boost/multi_index/detail/header_holder.hpp:41:16: error: expected unqualified-id before ')' token
       Final& final(){return *static_cast<Final*>(this);}

Maybe I am doing something wrong somewhere else, e.g. configuring TPIE incorrectly?

**Comment by hendrik-cliqz** [comment]
FYI the TPIE build command:

    cmake -D CMAKE_BUILD_TYPE:STRING=Release -D CMAKE_INSTALL_PREFIX=install -D TPIE_PARALLEL_SORT=1 -D CMAKE_CXX_FLAGS=-fPIC .. && make

**Comment by antialize** [comment]
You should not be able to miss configure tpie. If you would try to compile "https://github.com/thomasmoelhave/tpie/blob/master/cpp0xtest/override_keyword.cpp" with your version of g++, we can find out what goes on.

In you build folder there should be a file called tpie/config.h. If "cpp0xtest/override_keyword.cpp" compiles cleanly this file should contain the line "#define TPIE_CPP_OVERRIDE_KEYWORD"
and if it does not it should contain the line "/* #define TPIE_CPP_OVERRIDE_KEYWORD */"

In the latter case we will later redefine final an override to nothing. 

If it compiles cleanly, then

**Comment by hendrik-cliqz** [comment]
override_keyword.cpp only compiles with 
    
    g++ -std=c++11 override_keyword.cpp 

but not with 

    g++ override_keyword.cpp

as expected I guess.

the config.h look like this:

    ...
    /* #undef TPIE_CPP_VARIADIC_TEMPLATES */
    /* #undef TPIE_CPP_RVALUE_REFERENCE */
    /* #undef TPIE_CPP_OVERRIDE_KEYWORD */
    /* #undef TPIE_CPP_NOXECEPT_KEYWORD */
    /* #undef TPIE_CPP_DECLTYPE */
    /* #undef TPIE_CPP_TEMPLATE_ALIAS */
    /* #undef TPIE_CPP_NONE_POD_UNION */
    /* #undef TPIE_CPP_TYPE_TRAITS */

    #ifndef TPIE_CPP_OVERRIDE_KEYWORD
        #define final
        #define override
    #endif

**Comment by hendrik-cliqz** [comment]
Doing a recompile of TPIE I do not see a -std=c++11 in the gcc commands. So although I am not compiling TPIE with C++11??

**Comment by antialize** [comment]
Aha, try building with
cmake -D CMAKE_BUILD_TYPE:STRING=Release -D CMAKE_INSTALL_PREFIX=install -D TPIE_PARALLEL_SORT=1 -D CMAKE_CXX_FLAGS="-fPIC -std=c++11" .. && make

**Comment by hendrik-cliqz** [comment]
Yes, that fixes the issue as TPIE gets now compiled with C++11 and the config looks like this now:

    #define TPIE_CPP_VARIADIC_TEMPLATES
    #define TPIE_CPP_RVALUE_REFERENCE
    #define TPIE_CPP_OVERRIDE_KEYWORD
    /* #undef TPIE_CPP_NOXECEPT_KEYWORD */
    #define TPIE_CPP_DECLTYPE
    #define TPIE_CPP_TEMPLATE_ALIAS
    #define TPIE_CPP_NONE_POD_UNION
    #define TPIE_CPP_TYPE_TRAITS

    #ifndef TPIE_CPP_OVERRIDE_KEYWORD
        #define final
        #define override
    #endif

**Comment by antialize** [comment]
In 2.0 we will merge the c++11 branch, where this issue has been solved.

**Comment by svendcsvendsen** [comment]
The c++11 branch has now been fixed into master.
