### ISSUE TITLE
Document that the priority queue is a min queue.

### ISSUE THREAD

**Issue by antialize** [thomasmoelhave/tpie#185]
Currently it is not documented if the priority queue is a min or a max queue. I believe it is a min queue (@Mortal ?), in either case the documentation should clearly state what is the case.

**Comment by Mortal** [comment]
Who needs max queues! Yes, it is indeed a min queue.

**Comment by svendcsvendsen** [comment]
Now fixed in 3e126d89d3a07b93d24a84e77567afe49fb75524.
