### ISSUE TITLE
bug in disjoint_sets?

### ISSUE THREAD

**Issue by yjwoo14** [thomasmoelhave/tpie#188]
```clear()``` method only initializes ```m_size```. 
https://github.com/thomasmoelhave/tpie/blob/master/tpie/disjoint_sets.h#L156

```is_set(element)``` method uses the following condition ```m_elements[element] != m_unused```.
So, I think ```m_elements``` array should be initialized too.

**Comment by yjwoo14** [comment]
Also ```resize()``` has the same problem.

**Comment by svendcsvendsen** [comment]
Fixed in eb9c7b952d0644af697004134e9c4fb236f52548
