### ISSUE TITLE
Link to the website is dead

### ISSUE THREAD

**Issue by ilyaminkin** [thomasmoelhave/tpie#190]
This link, http://madalgo.au.dk/tpie/, leads to 404

**Comment by thomasmoelhave** [comment]
Thanks for the heads up, we're looking into it.

**Comment by Mortal** [comment]
Until this is fixed, the official mirror is http://users-cs.au.dk/rav/tpie/.

**Comment by Mortal** [comment]
Fixed.

**Comment by thomasmoelhave** [comment]
:+1:
