### ISSUE TITLE
Compressed stream causes crash in stack

### ISSUE THREAD

**Issue by Mortal** [thomasmoelhave/tpie#198]
Yujin has a program using a `tpie::stack` with sizeof(T) == 32, block size 2 MB, block items 65536. When run on some inputs (2*65536 + 1 pushes followed by 65536 + 1 pops), the compressor thread errors out because the compressed_stream calls read_previous_block which makes a backwards read_request for the compressor thread with block number 0, byte position 0 (which is invalid). This might be caused by m_readOffset and m_nextReadOffset not being updated after the stack has written some blocks.

**Comment by Mortal** [comment]
Jakob and I found a simpler test case that displays the error. We have pushed to master a test case with three streams A, B, C that are written and read backwards in lockstep (write two blocks to A, B and C simultaneously; read backwards A, B and C simultaneously). The test fails if and only if the third stream has compression enabled.

**Comment by Tyilo** [comment]
Calling `seek(0); read(); set_position(tpie::stream_position::end());` before reading the value backwards from the stream fixes the problem.

When using the above "fix" we read from position 4194 from the file and without it we read from position 4092 (`header_size() - sizeof(stream_header_t)`), which is obviously wrong.

**Comment by Tyilo** [comment]
Fixed in 3448e4d2923862c521f8a11fec810d591206a532.
The problem was that a call to `write` didn't update `m_readOffset`, so `read_back` would read at the wrong position.
