### ISSUE TITLE
Pipeline resource managment.

### ISSUE THREAD

**Issue by antialize** [thomasmoelhave/tpie#212]
It would be nice if the following code would work

```tp::virtual_chunk<int> method() {
  tp::passive_sorter<int> s1;
  return tp::virtual_chunk<int>(s1.input(), s2.output());
}```

However it is not clear currently if we need to keep the passive_sorter object around until the pipeline has been executed.  We have many such temp objects that we would like to not keep around, such as:
* passive_sorter
* passiver_buffer
* passive_reverser
* passive_serialization_sorter
* passive_serialization_buffer
* passive_serialization_reverser
* join
* split
* pipeline
* nodeset

**Comment by Tyilo** [comment]
Everything, but `pipeline` and `nodeset` can be safely dealloced before running the pipeline it seems.

Deallocing a `pipeline` causes a segfault later.

I haven't looked into `nodeset`, could you give me an example of how you would use `nodeset` as a temporary object?

**Comment by antialize** [comment]
Off the top of my head (does not compile)

template <typename T>
virtual_chunk <T> virtual_internal_buffer() {
  struct C : virtual_container {
    vector<T> v;
  };
  C * c = new C();
  node_set ns = make_node_set();
  auto s = virtual_chunk_end<T>(vector_sink(c->v).add_to_set(ns));
  auto e = virtual_chunk_begin<T>(vector_source(c->v).add_forwarding_dependencies(ns),
c);
  return virtual_chunk<T>(s, e);
}

/Jakob

**Comment by Tyilo** [comment]
We now don't need to keep any of those objects around as of 42e5ffb31c853b47a39ba8105648b848001b7dbc
