### ISSUE TITLE
Issue on compressed stream

### ISSUE THREAD

**Issue by yjwoo14** [thomasmoelhave/tpie#217]
While using reverse pipe (which uses tpie::stack), we have got an error "Bad buffer get_read_offset". 
Unfortunately, I couldn't reproduce this error with small input. 

However, I found that unit test ut-compressed-stream incur same error. (read_back_seek_2)

**Comment by Tyilo** [comment]
This bug was probably introduced (or never fixed) with the fix for #198. `read_back_seek_2` wasn't in the `CMakeLists.txt` file, so running `ctest` didn't run this test.

But I'll look into it.

**Comment by Tyilo** [comment]
The `read_back_seek_2` test now works as of 15822929f2d59dc4220fe0ee83c2695506b08115.

Could you check if this works with your reverse pipe?

**Comment by yjwoo14** [comment]
Thanks. 

Because the machine that has the input data is being used now, I will test it when the machine becomes available.

**Comment by yjwoo14** [comment]
Yes, it works! Thanks.
