### ISSUE TITLE
Write in docs that buffer, reverser, sorter items must be trivially copyable

### ISSUE THREAD

**Issue by Mortal** [thomasmoelhave/tpie#219]
It doesn't say explicitly in the pipelining docs when item types must be trivially copyable, and this has tripped up Yujin's code (trying to buffer and reverse streams of `tpie::arrays`).

**Comment by antialize** [comment]
Perhaps we should even go as far as to emit a compiler warning if they are not.  Cpp ref sayes:

The copy constructor for class T is trivial if all of the following are true:
    it is not user-provided (that is, it is implicitly-defined or defaulted), and if it is defaulted, its signature is the same as implicitly-defined (until C++14);
    T has no virtual member functions;
    T has no virtual base classes;
    the copy constructor selected for every direct base of T is trivial;
    the copy constructor selected for every non-static class type (or array of class type) member of T is trivial; 
    T has no non-static data members of volatile-qualified type.  (since C++14)

I think this holds for most types in terrastream, so perhaps we can even static_assert it.

**Comment by Mortal** [comment]
Well, if we want to go with `static_assert`, I think it would be more appropriate to check this in `file_stream` itself.

**Comment by Tyilo** [comment]
Currently in at least one test case and also in the pipelining framework we use `std::pair` as the item type for `file_stream`, which is problematic as `std::pair` is not required to be trivially copyable, so we can't just use `static_assert(std::is_trivially_copyable<T>::value, "...")` in `file_stream`.

Should we use our own `tpie::pair` instead of `std::pair` in all those places?

**Comment by Tyilo** [comment]
To avoid invoking undefined behaviour, I don't think trivially copyable is a strong enough requirement for the item type.
I think it only guarantees that we can `memcpy` it to another location, but not `reinterpret_cast`' a buffer like we do.

I have implemented the `static_assert` in c7e7735, which also allows `std::pair` item types.

**Comment by antialize** [comment]
We should probably check with terrastream before sending this to master. What would be wrong with our reinterpret casts? except it being undefined behaviour?

**Comment by Tyilo** [comment]
Well undefined behaviour is never nice, is it?

Another thing to note is that `is_trivially_copyable` is only supported in gcc version 5 or above, but we can currently compile tpie with gcc 4.8.

**Comment by antialize** [comment]
We can safely require that any compiler we support, supports c++11 if gcc 4.8 does not, then we should use another compiler in our tests.

**Comment by Tyilo** [comment]
Well gcc 4.8 supports c++11, but the version of libstdc++ that gcc 4.8 uses doesn't support all of c++11.

**Comment by Tyilo** [comment]
This has been implemented with a `static_assert`.
