### ISSUE TITLE
Cannot create more than 42 Tpie instances simultaneously

### ISSUE THREAD

**Issue by narek-cliqz** [thomasmoelhave/tpie#220]
We use `tpie` for external sorting in the [keyvi](https://github.com/cliqz-oss/keyvi) project.
And when we run it on big machines (128 core) we need to start more than 42 instance simultaneously. Unfortunately we hit the limit of `tpie` temporary directories created with a second. 
``` 
Unable to find free name for temporary folder.
```

**Comment by Mortal** [comment]
I think a better solution would be to use Boost to make a random directory name: http://stackoverflow.com/a/5988737
