### ISSUE TITLE
CTest is failed

### ISSUE THREAD

**Issue by Antonavt** [thomasmoelhave/tpie#229]
Hello,
After successfully compiling TPIE, I have run CTest and receive:

`
99% tests passed, 1 tests failed out of 263

Total Test time (real) =  30.02 sec

The following tests FAILED:
	102 - external_priority_queue_remove_group_buffer (Failed)
Errors while running CTest
`

I did so:
export CTEST_OUTPUT_ON_FAILURE=1
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug ..
make
make test

and received:
`102/263 Test #102: external_priority_queue_remove_group_buffer .......***Failed    0.13 sec
remove_group_buffer .................................................... [fail]
Unexpected TPIE exception: [Priority queue: Not enough memory. Increase allowed memory.]
`
It was run on a computer with 256gb RAM.  How to fix this test?

**Comment by antialize** [comment]
That test does indeed also fail for me. We will have @Tyilo look into it.
