### ISSUE TITLE
Tpie rendering examples

### ISSUE THREAD

**Issue by gijsde1ste** [thomasmoelhave/tpie#236]
Hi all,

I generally use SDL2 to render examples of what I'm working on but it seems incompatible with tpie. I can initialize a renderer and window and draw some very basic figures but immediatly after tpie throws random errors like "corrupted size vs. prev_size" or "Segmentation fault (core dumped)" and occasionally (I think sdl2 throws those) a floating point error.

Does anyone know a simple graphics library (ubuntu) for very simple drawing of lines that works well with tpie?

**Comment by Mortal** [comment]
Hi @gijsde1ste, if you can provide a small example of combining TPIE and SDL2 in an application where you get this error, then we can take a look. I only have limited experience with SDL2, but I don't think the two libraries should be fundamentally incompatible.

For a "simple graphics library for very simple drawing of lines", I don't have any good suggestion, but depending on what you need, you could go for something that outputs a vector graphics file that you can look at afterwards, e.g.

```c++
#include <fstream>

class SvgOut {
private:
	std::ofstream out;
public:
	SvgOut(std::string path): out(path) {
		out << "<!DOCTYPE html><svg width=\"300px\" height=\"150px\"><path fill=\"none\" stroke=\"black\" d=\"";
	}
	void move(float x, float y) {
		out << "M " << x << " " << y << " ";
	}
	void line(float x, float y) {
		out << "L " << x << " " << y << " ";
	}
	~SvgOut() {
		out << "\"></path></svg>\n";
	}
};

int main() {
	SvgOut svg("foo.html");
	svg.move(20, 10);
	svg.line(120, 20);
	svg.line(110, 110);
	svg.line(10, 100);
	svg.line(20, 10);
}
```

(Compile, run, and open foo.html in a browser with e.g. `firefox foo.html`)

**Comment by gijsde1ste** [comment]
Hi @Mortal, 

Sorry for getting back to you so late. After creating a minimal example it seems I'm not necessarily having issues with the rendering but instead with destruction of data structures. See the simple example attached, even when the draw call is commented it will give a segmentation error at the end of the main method, I assume when the stack gets destroyed.

I'm still pretty new to tpie, should I call any explicit method to close/clean a stack before c++ automatically destroys it because it went out of scope?

[main.zip](https://github.com/thomasmoelhave/tpie/files/4747585/main.zip)

**Comment by gijsde1ste** [comment]
@Mortal thanks for solving, should've known it was something like this.
