### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by markopy** [thomasmoelhave/tpie#243]
I'm considering using TPIE for a new project but it's not clear which version I should use.

There seems to be a lot of activity in this repository but the last released version linked on the website and tagged on  github is v1.1 from 2013.

Is v1.1 the stable, recommended version? Should I use the master branch in this repository? How stable would that be?

Maybe some guidance regarding this can be added to the website and/or the github README?

**Comment by antialize** [comment]
Since we do not have many users, except our selves we have not had any need to do releases. We run on top of head of master. Master is currently very stable and does not se many changse.

**Comment by antialize** [comment]
I have updated the readme.
