### ISSUE TITLE
Pipelining: Shorten progress fraction internal names

### ISSUE THREAD

**Issue by Mortal** [thomasmoelhave/tpie#35]
Right now, fractions in the progress indicator used by pipelining are stored with typeid(T).name() as the key, resulting in humongous names because of the nested templates used in pipelining. This is a problem since the keys are used in string comparisons, so we should make them shorter by some kind of hashing scheme.

**Comment by antialize** [comment]
This has now become somewhat more important since we switch to std::regex, which does not handle long strings well:
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67212 and
https://gcc.gnu.org/bugzilla/attachment.cgi?id=36184

**Comment by antialize** [comment]
Fixed in master
