### ISSUE TITLE
Compilation error in test_pipelining.cpp on MSVC 2012

### ISSUE THREAD

**Issue by thomasmoelhave** [thomasmoelhave/tpie#81]
I'm getting the following error from the Visual Studio 2012 compiler:

    60> tpie\test\unit\test_pipelining.cpp(217): error C2893: Failed to specialize function template 'tpie::pipelining::pipe_middle<tpie::pipelining::factory_1<tpie::pipelining::bits::merge_t<fact_t>::type,pull_t>> tpie::pipelining::merge(const tpie::pipelining::pullpipe_begin<fact_t> &)'
    60>          With the following template arguments:
    60>          'tpie::pipelining::termfactory_1<R,T1>'
    60>          with
    60>          [
    60>              R=tpie::pipelining::bits::pull_input_t<test_t>,
    60>              T1=tpie::file_stream<test_t> &
    60>          ]

This is on master.

**Comment by hexiaodongRUC** [comment]
This is still a problem in VS2013

error C3203:  'factory_1':unspecialized class type can't be used as a type argument

**Comment by Mortal** [comment]
I think this issue is hard to debug unless @svendcsvendsen or me or another template-typename-ninja actually sits down with a VS2012 / VS2013 installation.

Basically we need a minimal failing example, but with heavily templated C++ that can be hard to produce...

**Comment by svendcsvendsen** [comment]
It would be nice to have a Windows installation set up on a machine. I could get IT to set it up on the spare machine in my office.

**Comment by antialize** [comment]
That shoulds like a good idea.

**Comment by thomasmoelhave** [comment]
Have we more or less dropped support for older than 2015 vs versions?  We can close this ticket then.

**Comment by antialize** [comment]
Yes we have.

/Jakob
